### PR TITLE
Fix for wp_die() tests

### PR DESCRIPTION
**Pull request by benbalter**
This is a follow up to https://github.com/wp-document-revisions/wp-document-revisions/pull/251 to fix the `wp_die()` issue discovered in #250 which would cause tests to exit prematurely. 

At some point WP added a `wp_die_xml_handler` that was distinct from the `wp_die_handler`, which we weren't hooking in to to raise the expected exception when `wp_die()` is called on feeds. This adds an additional filter to properly raise for feeds, relying on the test framework's filter, and taking inspiration from the internet, moves to a `try`/`catch` model, instead of our bespoke `_wpdr_is_wp_die()` which used globals to track state.

### CODE REVIEW

**Comment by benbalter** [comment]
@NeilWJames Good news, I've gotten the `wp_die()` tests working as expected now! Bad news, [it seems there's a multisite failure](https://github.com/wp-document-revisions/wp-document-revisions/runs/2586664665) around the meta box. I'm stumped. Do you have any idea what might be causing that test failure now?

**Comment by NeilWJames** [comment]
Ben,
Very pleased that you have sorted the wp_die processing. I found it baffling why it didn't work as expected.

I don't know a great deal about Multisite. However looking at the issue, and folks complaining about it bringing a slug /blog/ into the permalink,
The failing test is where although the permalink is retrieved, it is then manipulated and created from different elements of the name - and the test is checking that this recreates the permalink. This process may be uncorrect for multisite.
I am happy to spend some time to try to sort this, However a slight timing problem. I am going away for a week tomorrow morning and will not be online
Regards,
Neil

**Comment by NeilWJames** [comment]
Ben,
I have got the tests to pass.
I believe that I need to look at the permalink format generated - and whether the construct of the URL needs modification because I cannot see a name like http://example.org/?post_type=document&#038;p=7&#038;revision=1.txt is correct.

I would also like to use the standard WP process to show Workflow_state on the documents list before you release the package. This will remove some special processing.

Thanks,
Neil

**Comment by benbalter** [comment]
> I have got the tests to pass... I believe that I need to look at the permalink format generated - and whether the construct of the URL needs modification because I cannot see a name like http://example.org/?post_type=document&#038;p=7&#038;revision=1.txt is correct.

Amazing. 🙏🏻 Thank you. I should have thought of that. Do we think the problem is with how we generate permalinks in multisite or is that just a multisite-specific quirk?

> I would also like to use the standard WP process to show Workflow_state on the documents list before you release the package. This will remove some special processing.

:+1:. That makes sense. I'm going to merge this PR since it gets the full suite of tests passing on the main branch, and we can implement the `workflow_state` in a separate PR before we cut a new release.

> I am going away for a week tomorrow morning and will not be online

I hope your time away from the computer was good. Thanks again for taking the time to tackle this perplexing issue.

**Comment by benbalter** [comment]
> I have got the tests to pass... I believe that I need to look at the permalink format generated - and whether the construct of the URL needs modification because I cannot see a name like http://example.org/?post_type=document&#038;p=7&#038;revision=1.txt is correct.

Amazing. 🙏🏻 Thank you. I should have thought of that. Do we think the problem is with how we generate permalinks in multisite or is that just a multisite-specific quirk?

> I would also like to use the standard WP process to show Workflow_state on the documents list before you release the package. This will remove some special processing.

:+1:. That makes sense. I'm going to merge this PR since it gets the full suite of tests passing on the main branch, and we can implement the `workflow_state` in a separate PR before we cut a new release.

> I am going away for a week tomorrow morning and will not be online

I hope your time away from the computer was good. Thanks again for taking the time to tackle this perplexing issue.

**Pull request merged**
